---------------------------------------------------------------------------------------
-- QCM PROJECT
-- Gestion du script de création de la base de données.
---------------------------------------------------------------------------------------


USE [master]
GO

/****** Object:  Database [QCM_Project]    Script Date: 03/25/2011 15:59:09 ******/
CREATE DATABASE [QCM_Project] ON  PRIMARY 
( NAME = N'QCM_Project', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\QCM_Project.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QCM_Project_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\QCM_Project_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QCM_Project] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QCM_Project].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QCM_Project] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QCM_Project] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QCM_Project] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QCM_Project] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QCM_Project] SET ARITHABORT OFF 
GO

ALTER DATABASE [QCM_Project] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QCM_Project] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [QCM_Project] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QCM_Project] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QCM_Project] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QCM_Project] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QCM_Project] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QCM_Project] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QCM_Project] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QCM_Project] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QCM_Project] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QCM_Project] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QCM_Project] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QCM_Project] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QCM_Project] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QCM_Project] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QCM_Project] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QCM_Project] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QCM_Project] SET  READ_WRITE 
GO

ALTER DATABASE [QCM_Project] SET RECOVERY FULL 
GO

ALTER DATABASE [QCM_Project] SET  MULTI_USER 
GO

ALTER DATABASE [QCM_Project] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QCM_Project] SET DB_CHAINING OFF 
GO

